#!/bin/bash

# Run cargo fmt in check mode
cargo fmt --manifest-path circuit/Cargo.toml -- --check || { echo "Please run 'cargo fmt' in circuit/"; exit 1; }
cargo fmt --manifest-path prover-service/Cargo.toml -- --check || { echo "Please run 'cargo fmt' in prover-service/"; exit 1; }
cargo fmt --manifest-path keyless-common/Cargo.toml -- --check || { echo "Please run 'cargo fmt' in keyless-common/"; exit 1; }
cargo fmt --manifest-path vk-diff/Cargo.toml -- --check || { echo "Please run 'cargo fmt' in vk-diff/"; exit 1; }

# Check the result
if [ $? -ne 0 ]; then
  echo "Error: 'cargo fmt' check failed in circuit/src."
  echo "Please run 'cargo fmt' in circuit/src and stage the changes."
  exit 1
fi

# Check if any .circom files in 'circuit/templates' changed
if git diff --cached --name-only | grep -q '^circuit/templates/.*\.circom$'; then
    echo "Detected changes in *.circom files!"
    echo
    echo "Running circom compilation. This will take ~45 seconds..."

    # Move into the circuit/templates directory
    pushd circuit/templates > /dev/null

    # Run your circom command
    time circom --O0 -l "$(npm root -g)" main.circom --r1cs

    # Check if circom command succeeded
    if [ $? -ne 0 ]; then
        echo "Error: circom compilation failed. Commit aborted."
        popd > /dev/null
        exit 1
    fi

    echo "circom compilation succeeded."
    popd > /dev/null
fi

exit 0
